[features]
seeds = false
skip-lint = false
[programs.localnet]
animal_kingdom = "Bco4dXjvoM1oPsU5c2u8rDKXesq2r9iKoM6cSGz53i87"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/home/rayhan/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
